using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BUS;

namespace BTL_QUANLYSINHVIEN
{
    public partial class frmDiemSinhVien : Form
    {
        public string MaSV="", TenSV="";
        public frmDiemSinhVien()
        {
            InitializeComponent();
            
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
        }

        private void btnXemDiem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            btnXuatExcel.Enabled = true;
            btnLuuDiem.Enabled = false;
            btnHuy.Enabled = false;
            if (cboKyHoc.Text.Trim() == "Tất cả")
            {
                load();
            }
            else
            {
                loadKyhoc();
            }
        }
        private void load()
        {
            try
            {
                SVbindingSource.DataSource = SinhVien_BUS.phieuDiemSV(MaSV);
                gcSV.DataSource = SVbindingSource;
            }
            catch
            {
                MessageBox.Show("Load điểm bị lỗi!");
            }
        }
        private void loadKyhoc()
        {
            try
            {
                int kyHoc = Convert.ToInt32(cboKyHoc.Text.Trim());
                SVbindingSource.DataSource = SinhVien_BUS.phieuDiemSV_kyHoc(MaSV,kyHoc);
                gcSV.DataSource = SVbindingSource;
            }
            catch
            {
                MessageBox.Show("Load điểm bị lỗi!");
            }
        }
        public void   loadInfo()
        {
            cboKyHoc.SelectedIndex = 0;
            tbMaSV.Text = MaSV;
            tbTenSV.Text = TenSV;
            btnLuuDiem.Enabled = false;
            btnHuy.Enabled = false;
            btnXuatExcel.Enabled = false;
            DataTable dtb = SinhVien_BUS.kyHocSV(MaSV);
            int soKy = cboKyHoc.Items.Count;
            for(int i=1;i<soKy;i++)
            {
                cboKyHoc.Items.RemoveAt(1);
            }
            for(int i=0;i<dtb.Rows.Count;i++)
            {
                string kyHoc=dtb.Rows[i][0].ToString();
                cboKyHoc.Items.Add(kyHoc);
            }
            gcSV.RefreshDataSource();
            int t = SVbindingSource.Count;
            for (int i = 0; i < t; i++)
                SVbindingSource.RemoveAt(0);
        }

        private void btnRefresh_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            loadInfo();
        }
    }
}
